/**
 * Emit the whole migration history as ONE .sql file you can paste into the
 * Supabase SQL editor.
 *
 *     npx tsx scripts/emit-migration-sql.ts            # -> migrations-all.sql
 *     npx tsx scripts/emit-migration-sql.ts out.sql
 *
 * Why this exists: `npm run db:migrate --env prod` requires an interactive
 * operator typing PROD, by design (P2.2r). That is the right guard, but it
 * needs a real terminal and the right env var in the same shell. This is the
 * escape hatch that does not weaken it — the ceremony is replaced by the
 * operator deliberately pasting SQL into their own database's console, which
 * is at least as deliberate an act.
 *
 * It writes NO connection string and touches no database. The output is plain
 * SQL; the destination is chosen by whichever SQL editor you paste it into.
 *
 * Bookkeeping is included: the file creates `drizzle.__drizzle_migrations` and
 * inserts each migration's sha256 + created_at, exactly as scripts/migrate.ts
 * would. After running it, `npm run db:migrate --env prod` reports
 * "already applied" for every file rather than trying to re-run them.
 *
 * Idempotency: every insert is guarded by `where not exists`, and the file is
 * wrapped in a single transaction, so a partial paste rolls back rather than
 * leaving a half-migrated database.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import { plan } from "./migration-plan";

function main(argv: string[]): number {
  const outPath = path.resolve(argv[0] ?? "migrations-all.sql");
  const migrations = plan();

  const parts: string[] = [
    "-- Provency: full migration history, generated by scripts/emit-migration-sql.ts",
    "-- Paste into the Supabase SQL editor of the TARGET project and run once.",
    "--",
    `-- ${migrations.length} migrations, in dependency order. The out-of-band`,
    "-- 0005_auth_ownership_rls runs after 0004 because 0012 alters profiles,",
    "-- which only that file creates.",
    "--",
    "-- Wrapped in a transaction: if anything fails, nothing is applied.",
    "",
    "begin;",
    "",
    "create schema if not exists drizzle;",
    `create table if not exists drizzle.__drizzle_migrations (
  id serial primary key,
  hash text not null,
  created_at bigint
);`,
    "",
    "-- Refuse to replay into a database that already has migrations. Drizzle's",
    "-- CREATE TYPE statements are not idempotent, so a second paste would fail",
    "-- deep in the file with a confusing error; fail here instead, before",
    "-- anything is attempted. Inside the transaction, so nothing is applied.",
    `do $guard$
begin
  if exists (select 1 from drizzle.__drizzle_migrations) then
    raise exception
      'This database already has % recorded migration(s). Refusing to replay the whole history. Use: npm run db:migrate --env prod',
      (select count(*) from drizzle.__drizzle_migrations);
  end if;
end
$guard$;`,
    "",
  ];

  for (const m of migrations) {
    parts.push(
      `-- ─────────────────────────────────────────────────────────────────────`,
      `-- ${m.tag}${m.outOfBand ? "   (out-of-band: not in the Drizzle journal)" : ""}`,
      `-- sha256 ${m.hash}`,
      `-- ─────────────────────────────────────────────────────────────────────`,
      "",
    );
    for (const stmt of m.statements) {
      parts.push(stmt.endsWith(";") ? stmt : `${stmt};`, "");
    }
    // Record it the way drizzle-kit does, so a later db:migrate is a no-op.
    parts.push(
      `insert into drizzle.__drizzle_migrations (hash, created_at)
select '${m.hash}', ${m.createdAt}
where not exists (
  select 1 from drizzle.__drizzle_migrations where hash = '${m.hash}'
);`,
      "",
    );
  }

  parts.push("commit;", "");
  writeFileSync(outPath, parts.join("\n"), "utf8");

  const statements = migrations.reduce((n, m) => n + m.statements.length, 0);
  console.log(`wrote ${outPath}`);
  console.log(`  ${migrations.length} migrations, ${statements} statements`);
  for (const m of migrations) {
    console.log(`    ${m.tag}${m.outOfBand ? "  (out-of-band)" : ""}`);
  }
  console.log("\nPaste it into the SQL editor of the TARGET project and run once.");
  console.log("Afterwards `npm run db:migrate --env prod` should report every file");
  console.log("as already applied.");
  return 0;
}

process.exit(main(process.argv.slice(2)));
